### ISSUE TITLE
Login difficulty with 4.0.0

### ISSUE THREAD

**Issue by queenvictoria** [auth0-community/ember-simple-auth-auth0#116]
Hi there. Thanks for the awesome work! I've been using the addon in a number of projects.

I'm in process of upgrading to 4.0.0 and Lock 11. But have been having some pretty serious difficulties getting it to work. So I've installed a fresh version of Ember to debug and used the code samples from the README verbatim. Unfortunately this produces the same errors.

The issue is that, when pressing a login action, everything fires off ok but I'm returned to the login page (`application.hbs`).

The only way to get around it (it seems) is to use the vanilla `ember-simple-auth` mixin instead of the Auth0 mixin.
`import ApplicationRouteMixin from 'ember-simple-auth-auth0/mixins/application-route-mixin';`

`import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';`

What is the best way to debug whats going on do you think?

**Comment by peavers** [comment]
This sounds very similar to the issues I'm having [@114](https://github.com/auth0-community/ember-simple-auth-auth0/issues/114).

**Comment by queenvictoria** [comment]
@peavers yeah I thought so too. Similar symptoms, similar fix. Though I can't double login to solve the issue. And I can't use `ember-simple-auth` as I'm trying to enable impersonation.

Should I close this and append to #114? 

I'm wondering if its configuration at Auth0.

Weird thing is: it looks like I 'solved' this in < 4.0 by doing just that--replacing it with `ember-simple-auth`. So it may exist before 4.x too.

**Comment by queenvictoria** [comment]
Hi @XaserAcheron thanks for taking a look. I've pushed up the repo.
https://github.com/queenvictoria/test-ember-simple-auth-auth0

One thing I have noticed is that with new Auth0 accounts some options are no longer available. So I wonder if there are minor differences that can be causing this as I've moved to a new account and client (which is why I'm upgrading).

```
$ npm install
$ export AUTH0_CLIENTID="xxxxxxx"
$ export AUTH0_DOMAIN="xxxxxxxx.auth0.com"
$ ember s
```

**Comment by XaserAcheron** [comment]
Whew! Thanks for the help. Managed to get to the bottom of this -- it's _sorta_ account settings related. Here's the gist:

- Auth0 issues two primary types of tokens: [Access Tokens](https://auth0.com/docs/tokens/access-token) and [ID Tokens](https://auth0.com/docs/tokens/id-token).
- When the OIDC Conformant flag is switched on in Client Settings (on your Auth0 account), the ID Token is not sent unless explicitly requested by the client (i.e. Lock).
- `ember-simple-auth-auth0` tries to fetch a claim (`iat`, the issued-at timestamp) from the ID Token to calculate session expiration time. Since it's null, this calculation yields "zero seconds until expiration."
- The session expires instantly.

So what you're seeing is a successful authentication... followed by an immediate expiration. D:

For now, it's possible to work around this by explicitly requesting the `id_token` in the Lock options hash (via `responseType`), like so:
```js
// ...
      const lockOptions = {
       auth: {
         responseType: 'token id_token'
       }
      };

      get(this, 'session').authenticate('authenticator:auth0-lock', lockOptions);
// ...
```

I've got a proper fix in progress, but the expiration stuff has been enough of a thorn in my side that I'm taking the time to review & refactor it. About time, I suppose.

Apologies for this -- I missed this because I've always used the ID Token for stuff in my own apps & test cases. Pitfalls of inheriting an existing project with a lot of use cases.

**Comment by XaserAcheron** [comment]
Excellent! :D

**Comment by queenvictoria** [comment]
That also fixes my scenario thank you @XaserAcheron ! Should we close this one?

(now back to figuring out why impersonation isn't working ;)

**Comment by XaserAcheron** [comment]
@queenvictoria Hmm, you may be right. There's a proper fix pending in PR #117, so no need to close this just yet (it is indeed a bug). That'd be a great thing to try out once it's all merged + released!

**Comment by XaserAcheron** [comment]
Just released `v4.0.1`, which should fix this for real now. Hope this helps!

**Comment by XaserAcheron** [comment]
Welp. I missed a spot, so `v4.0.2` is a thing now. Be sure to use that version else you'll run into a different instance of everyone's favorite zero-second-timeout bug. :P

**Comment by queenvictoria** [comment]
Nice work! I did just get another double / loop login issue and upgrading to `v4.0.2` did fix it! Thanks @XaserAcheron
