### ISSUE TITLE
Silent Authentication only run when refresh the page

### ISSUE THREAD

**Issue by EUGinsane** [auth0-community/ember-simple-auth-auth0#160]
So previously on #159 I asked if this addon support silent authentication, and thanks to @XaserAcheron I can implement it. But there is only one issue, I have to refresh the page manually after the session is authenticated to make it run. Have anyone faced this one before ? Thanks

**Comment by XaserAcheron** [comment]
Could you post a runnable sample project showing the issue?

**Comment by XaserAcheron** [comment]
Just had a quick thought -- make sure your application route uses the `ApplicationRouteMixin` from `ember-simple-auth-auth0`, _not_ the one from `ember-simple-auth` one, e.g.:

`import ApplicationRouteMixin from 'ember-simple-auth-auth0/mixins/application-route-mixin';`

If you're instead importing `ember-simple-auth/mixins/application-route-mixin`, then that could lead to issues like renewals not working. It's a bit confusing, and I think the docs ought to be much more clear about this, since this appears to be a common pain point.

Just a hunch; lemme know if it helps though!

**Comment by EUGinsane** [comment]
I checked everything @XaserAcheron, I am using exact code as described in README before.

![image](https://user-images.githubusercontent.com/30293222/56704800-bc825b80-6738-11e9-8e68-df1db5d2712c.png)

But it runs only after I refresh the page or open the page in new tab :( I am working on a company project so it is not okay for me to share you the code. I will try to make a new ember app and see what will happen.

**Comment by EUGinsane** [comment]
I checked to the Auth0 Logs and it always shows `Failed Silent Auth`

![image](https://user-images.githubusercontent.com/30293222/56707643-e8efa500-6743-11e9-84ac-a0ec6150adcb.png)
![image](https://user-images.githubusercontent.com/30293222/56707670-002e9280-6744-11e9-8255-a7a75badf5fb.png)
![image](https://user-images.githubusercontent.com/30293222/56707682-091f6400-6744-11e9-8c5e-6c28984df1cd.png)

**Comment by XaserAcheron** [comment]
Ah, OK -- well, for better or worse, that means this addon is working as intended. That's the error Auth0 sends back when the user isn't allowed to use silent authentication -- the reasons are numerous, and there's not much I can do to help.

All I can think of offhand is to make sure [SSO](https://auth0.com/docs/sso/current) is set up properly (Silent Auth needs that to work) -- beyond that, you're best contacting Auth0 support.
