### ISSUE TITLE
user_metadata is undefined on login

### ISSUE THREAD

**Issue by peavers** [auth0-community/ember-simple-auth-auth0#95]
Using the following lock options, then attempting to access the users metadata returns undefined
```js
    login() {
      const lockOptions = {
        avatar: null,
        container: "login-container",
        oidcConformant: true,
        hashCleanup: true,
        auth: {
          audience: "http://...",
          params: {
            scope: 'openid profile user_metadata',
            responseType: 'id_token token',
          }
        }
      };
      get(this, 'session').authenticate('authenticator:auth0-lock', lockOptions);
    },
```
Then trying to access user_metadata 
```js
let metadata = get(this, 'session.data.authenticated.profile.user_metadata.custom_data');
```
Returns undefined, note it's only user_metadata I can't access. Profile data is fine. 

Further reading, and this is a change to the core auth0 framework as outlined here https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims

> ...Note that the user_id property is sent as sub in the ID token, and that favorite_color and user_metadata are not present in the OIDC response from Auth0.

Looks like this can be fixed/solved with custom rules in Auth0 such as 
```js
function (user, context, callback) {
  const namespace = 'https://myapp.example.com/';
  context.idToken[namespace + 'favorite_color'] = user.favorite_color;
  context.idToken[namespace + 'preferred_contact'] = user.user_metadata.preferred_contact;
  callback(null, user, context);
}
```

**Comment by XaserAcheron** [comment]
Thanks for the report -- there isn't anything we can do about this directly, unfortunately, since the changes (and the solution) are all on Auth0's side. The custom rule is indeed the way to go.

I've opened an issue (#99) for documenting this better, though, since this indeed looks like it'll trip folks up who are moving to the OIDC-conformant workflow (which will be mandatory in v4.0.0 since Auth0's retiring the old one). Hopefully that will help a bit.
